apps/tiket/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from apps.tiket import views

urlpatterns = [
	path('manage/update/<int:pk>', views.TiketUpdateView.as_view(), name='update'),
	path('manage/delete/<int:pk>', views.TiketDeleteView.as_view(), name='delete'),
	path('manage/', views.TiketManageView.as_view(), name='manage'),
	path('tambahmove/<int:pk>', views.MoveStateCreateView.as_view(), name='createmove'),
	path('tambah/', views.TiketCreateView.as_view(), name='create'),
	path('detail/<str:slug>', views.TiketDetailView.as_view(), name='detail'),
	path('detailmove/<int:pk>', views.MoveStateDetailView.as_view(), name='detailmove'),
	path('tiketopen/<int:pk>', views.TiketNotDoneYet.as_view(), name='tiketopen'),
	path('tiketclosed/<int:pk>', views.TiketDone.as_view(), name='tiketclosed'),
	path('makepdf/', views.show_tiket, name='makepdf'),
	path('createpdf/', views.pdf_report, name='createpdf'),
	path('', views.TiketMoveView.as_view(), name='listmove' ),
	# path('', views.TiketListView.as_view(), name='list' ),

	#export file

	# path('listm/', views.TiketListMahasiswa.as_view(), name='listmahasiswa' ),
	# path('delete/<int:delete_id>', TiketDeleteView.as_view(), name='delete'),
	# path('update/<int:update_id>', TiketFormView.as_view(mode='update'), name='update'),
	# path('create/', TiketFormView.as_view(), name='create'),
	# path('', TiketListView.as_view(), name='list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("tiket/", include(("apps.tiket.urls", "apps.tiket"), namespace='tiket')),
    path("", include("apps.authentication.urls",)), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include(("apps.home.urls", "apps.home"), namespace='home'))

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">Datta Able</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <!-- <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li> -->
            <!-- <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li> -->
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            {% if not request.user.mahasiswa.nim %}
                                <img src="/static/assets/images/user/avatar-4.jpg" class="img-radius" alt="User-Profile-Image">
                            {% else %}
                                <img src="{{ ASSETS_ROOT }}{{request.user.mahasiswa.foto.url}}" class="img-radius" alt="User-Profile-Image">
                            {% endif %}
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="{% url 'logout' %}" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            {% if request.user.mahasiswa.nim %}
                                <li><a href="{% url 'profile2' %}" class="dropdown-item"><i class="feather icon-user"></i>
                                Profile</a></li>
                            {% endif %}
                            <li><a href="{% url 'logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

apps/templates/includes/scripts.html
<script src="{{ ASSETS_ROOT }}/js/vendor-all.min.js"></script>
<script src="{{ ASSETS_ROOT }}/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/pcoded.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/dark-mode.js"></script>
<script src="{{ ASSETS_ROOT }}/js/datatables/datatables3.min.js"></script>

apps/templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="/" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-type"></i>
                </div>
                <span class="b-title">Ticketing System</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Dashboard</span></a>
                </li>
<!--                 <li data-username="Profile Page" 
                    class="nav-item ">
                    <a href="{% url 'profile2' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                            <span class="pcoded-mtext">Profile Page</span></a>
                </li> -->
                <li class="nav-item pcoded-menu-caption">
                    <label>Ticket Menu</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Ticket</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'tiket:listmove' %}" class="">All Ticket</a></li>
                        <li class=""><a href="{% url 'tiket:create' %}" class="">Add Ticket</a></li>
                        <li class=""><a href="{% url 'tiket:manage' %}" class="">Manage Ticket</a></li>
                    </ul>
                </li>
                <!-- <li class="nav-item pcoded-menu-caption">
                    <label>UI Element</label>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu ">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/bc_button.html" class="">Button</a></li>
                        <li class=""><a href="/bc_badges.html" class="">Badges</a></li>
                        <li class=""><a href="/bc_breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                        <li class=""><a href="/bc_collapse.html" class="">Collapse</a></li>
                        <li class=""><a href="/bc_tabs.html" class="">Tabs & pills</a></li>
                        <li class=""><a href="/bc_typography.html" class="">Typography</a></li>


                        <li class=""><a href="/icon-feather.html" class="">Feather<span
                                class="pcoded-badge label label-danger">NEW</span></a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Forms & table</label>
                </li>
                <li data-username="form elements advance componant validation masking wizard picker select"
                    class="nav-item {% if 'form_elements' in segment %} active {% endif %}">
                    <a href="/form_elements.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-file-text"></i></span><span
                            class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable" 
                    class="nav-item {% if 'tbl_bootstrap' in segment %} active {% endif %}">
                    <a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Chart & Maps</label>
                </li>
                <li data-username="Charts Morris" 
                    class="nav-item {% if 'chart-morris' in segment %} active {% endif %}">
                    <a href="/chart-morris.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
                </li>
                <li data-username="Maps Google" 
                    class="nav-item {% if 'map-google' in segment %} active {% endif %}">
                    <a href="/map-google.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-map"></i></span><span
                        class="pcoded-mtext">Maps</span></a></li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
                            class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/register.html" class="" target="_blank">Sign UP</a></li>
                        <li class=""><a href="/login.html" class="" target="_blank">Sign IN</a></li>
                    </ul>
                </li>

                <li data-username="Sample Page" class="nav-item"><a href="/page-blank.html" class="nav-link"><span
                        class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>More Resources</label>
                </li>
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="https://appseed.us/support" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-headphones"></i>
                        </span>
                        <span class="pcoded-mtext">Support</span>
                    </a>
                </li> -->
                <li class="nav-item pcoded-menu-caption">
                    <label>Logout System</label>
                </li>                
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="https://bkui.ums.ac.id/" class="nav-link" target="blank">
                        <span class="pcoded-micon"><i class="feather icon-globe"></i></span><span class="pcoded-mtext">BKUI Website</span>
                    </a>
                </li>                
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->

apps/templates/includes/sidebar_kaur.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="/" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-type"></i>
                </div>
                <span class="b-title">Ticketing System</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Dashboard</span></a>
                </li>
<!--                 <li data-username="Profile Page" 
                    class="nav-item ">
                    <a href="{% url 'profile2' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                            <span class="pcoded-mtext">Profile Page</span></a>
                </li> -->
                <li class="nav-item pcoded-menu-caption">
                    <label>Ticket Menu</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Ticket</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'tiket:listmove' %}" class="">All Ticket</a></li>
                        <li class=""><a href="{% url 'tiket:manage' %}" class="">Manage Ticket</a></li>
                    </ul>
                </li>
             <!--    <li class="nav-item pcoded-menu-caption">
                    <label>UI Element</label>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu ">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/bc_button.html" class="">Button</a></li>
                        <li class=""><a href="/bc_badges.html" class="">Badges</a></li>
                        <li class=""><a href="/bc_breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                        <li class=""><a href="/bc_collapse.html" class="">Collapse</a></li>
                        <li class=""><a href="/bc_tabs.html" class="">Tabs & pills</a></li>
                        <li class=""><a href="/bc_typography.html" class="">Typography</a></li>


                        <li class=""><a href="/icon-feather.html" class="">Feather<span
                                class="pcoded-badge label label-danger">NEW</span></a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Forms & table</label>
                </li>
                <li data-username="form elements advance componant validation masking wizard picker select"
                    class="nav-item {% if 'form_elements' in segment %} active {% endif %}">
                    <a href="/form_elements.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-file-text"></i></span><span
                            class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable" 
                    class="nav-item {% if 'tbl_bootstrap' in segment %} active {% endif %}">
                    <a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Chart & Maps</label>
                </li>
                <li data-username="Charts Morris" 
                    class="nav-item {% if 'chart-morris' in segment %} active {% endif %}">
                    <a href="/chart-morris.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
                </li>
                <li data-username="Maps Google" 
                    class="nav-item {% if 'map-google' in segment %} active {% endif %}">
                    <a href="/map-google.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-map"></i></span><span
                        class="pcoded-mtext">Maps</span></a></li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
                            class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/register.html" class="" target="_blank">Sign UP</a></li>
                        <li class=""><a href="/login.html" class="" target="_blank">Sign IN</a></li>
                    </ul>
                </li>

                <li data-username="Sample Page" class="nav-item"><a href="/page-blank.html" class="nav-link"><span
                        class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>More Resources</label>
                </li>
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="https://appseed.us/support" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-headphones"></i>
                        </span>
                        <span class="pcoded-mtext">Support</span>
                    </a>
                </li>  -->
                <li class="nav-item pcoded-menu-caption">
                    <label>Logout System</label>
                </li>
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="https://bkui.ums.ac.id/" class="nav-link" target="blank">
                        <span class="pcoded-micon"><i class="feather icon-globe"></i></span><span class="pcoded-mtext">BKUI Website</span>
                    </a>
                </li>               
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->

apps/templates/includes/sidebar_mahasiswa.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="/" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-type"></i>
                </div>
                <span class="b-title">Ticketing System</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Dashboard</span></a>
                </li>
                <li data-username="Profile Page" 
                    class="nav-item ">
                    <a href="{% url 'profile2' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                            <span class="pcoded-mtext">Profile Page</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Ticket Menu</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Ticket</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'tiket:listmove' %}" class="">All Ticket</a></li>
                        <li class=""><a href="{% url 'tiket:create' %}" class="">Add Ticket</a></li><!-- 
                        <li class=""><a href="{% url 'tiket:listmove' %}" class="">View Ticket</a></li> -->
                        <!-- <li class=""><a href="{% url 'tiket:manage' %}" class="">Manage Tiket</a></li> -->
                    </ul>
                </li>
                <!-- <li class="nav-item pcoded-menu-caption">
                    <label>UI Element</label>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu ">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/bc_button.html" class="">Button</a></li>
                        <li class=""><a href="/bc_badges.html" class="">Badges</a></li>
                        <li class=""><a href="/bc_breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                        <li class=""><a href="/bc_collapse.html" class="">Collapse</a></li>
                        <li class=""><a href="/bc_tabs.html" class="">Tabs & pills</a></li>
                        <li class=""><a href="/bc_typography.html" class="">Typography</a></li>


                        <li class=""><a href="/icon-feather.html" class="">Feather<span
                                class="pcoded-badge label label-danger">NEW</span></a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Forms & table</label>
                </li>
                <li data-username="form elements advance componant validation masking wizard picker select"
                    class="nav-item {% if 'form_elements' in segment %} active {% endif %}">
                    <a href="/form_elements.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-file-text"></i></span><span
                            class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable" 
                    class="nav-item {% if 'tbl_bootstrap' in segment %} active {% endif %}">
                    <a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Chart & Maps</label>
                </li>
                <li data-username="Charts Morris" 
                    class="nav-item {% if 'chart-morris' in segment %} active {% endif %}">
                    <a href="/chart-morris.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
                </li>
                <li data-username="Maps Google" 
                    class="nav-item {% if 'map-google' in segment %} active {% endif %}">
                    <a href="/map-google.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-map"></i></span><span
                        class="pcoded-mtext">Maps</span></a></li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
                            class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/register.html" class="" target="_blank">Sign UP</a></li>
                        <li class=""><a href="/login.html" class="" target="_blank">Sign IN</a></li>
                    </ul>
                </li>

                <li data-username="Sample Page" class="nav-item"><a href="/page-blank.html" class="nav-link"><span
                        class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>More Resources</label>
                </li>
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="https://appseed.us/support" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-headphones"></i>
                        </span>
                        <span class="pcoded-mtext">Support</span>
                    </a>
                </li>   -->              
                <li class="nav-item pcoded-menu-caption">
                    <label>Logout System</label>
                </li>                
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="https://bkui.ums.ac.id/" class="nav-link" target="blank">
                        <span class="pcoded-micon"><i class="feather icon-globe"></i></span><span class="pcoded-mtext">BKUI Website</span>
                    </a>
                </li>
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->