apps/tiket/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from apps.tiket import views

urlpatterns = [
	path('manage/update/<int:pk>', views.TiketUpdateView.as_view(), name='update'),
	path('manage/delete/<int:pk>', views.TiketDeleteView.as_view(), name='delete'),
	path('manage/', views.TiketManageView.as_view(), name='manage'),
	path('tambahmove/<int:pk>', views.MoveStateCreateView.as_view(), name='createmove'),
	path('tambah/', views.TiketCreateView.as_view(), name='create'),
	path('detail/<str:slug>', views.TiketDetailView.as_view(), name='detail'),
	path('detailmove/<int:pk>', views.MoveStateDetailView.as_view(), name='detailmove'),
	path('tiketopen/<int:pk>', views.TiketNotDoneYet.as_view(), name='tiketopen'),
	path('tiketclosed/<int:pk>', views.TiketDone.as_view(), name='tiketclosed'),
	path('makepdf/', views.show_tiket, name='makepdf'),
	path('createpdf/', views.pdf_report, name='createpdf'),
	path('', views.TiketMoveView.as_view(), name='listmove' ),
	# path('', views.TiketListView.as_view(), name='list' ),

	#export file

	# path('listm/', views.TiketListMahasiswa.as_view(), name='listmahasiswa' ),
	# path('delete/<int:delete_id>', TiketDeleteView.as_view(), name='delete'),
	# path('update/<int:update_id>', TiketFormView.as_view(mode='update'), name='update'),
	# path('create/', TiketFormView.as_view(), name='create'),
	# path('', TiketListView.as_view(), name='list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("tiket/", include(("apps.tiket.urls", "apps.tiket"), namespace='tiket')),
    path("", include("apps.authentication.urls",)), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include(("apps.home.urls", "apps.home"), namespace='home'))

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tiket/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import TiketModel, Mahasiswa, MoveState, State

class MoveStateForm(forms.ModelForm):
	# tiket_move = forms.ModelChoiceField(queryset=TiketModel.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
	state_move = forms.ModelChoiceField(queryset=State.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
	comment = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'class':'form-control'}))
	# tiket_move = ModelChoiceField(queryset=TiketModel.objects.all())
	class Meta:
		model = MoveState
		fields = ['state_move', 'comment']

class ConfirmationForm(forms.ModelForm):
	# tiket_move = forms.ModelChoiceField(queryset=TiketModel.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
	# state_move = forms.ModelChoiceField(queryset=State.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
	comment = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'class':'form-control'}))
	# tiket_move = ModelChoiceField(queryset=TiketModel.objects.all())
	class Meta:
		model = MoveState
		fields = ['comment']

	# tiket_move = forms.ChoiceField(choices=tiket_move, widget=forms.Select(attrs={"class": "form-control"}))

class UpdateUserForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))

	class Meta:
		model = User
		fields = ['username' ,'first_name', 'last_name', 'email']


JURUSAN = [
	('Informatika', 'Informatika'),
	('Ilmu Komunikasi', 'Ilmu Komunikasi'),
	('Tekanik', 'Tekanik'),
	('Psikologi', 'Psikologi'),
]
class MahasiswaForm(forms.ModelForm):
	class Meta:
		model = Mahasiswa
		fields = [
			'nim',
			# 'nama',
			'jurusan',
			'no_hp',
			'foto',
		]
		nim = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
		jurusan = forms.ChoiceField(choices=JURUSAN, widget=forms.Select(attrs={'class':'form-control'}))
		no_hp = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control'}))
		foto = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control'}))

KATEGORI_LIST = [
		('visa', 'Visa'),
		('dokumen', 'dokumen'),
		('nilai', 'nilai'),
	]

# STATUS = [
# 		('pending', 'pending'),
# 		('open', 'open'),
# 		('process', 'process'),
# 		('finish', 'finish'),
# 		('closed', 'closed'),
# 	]
class TiketForm(forms.ModelForm):
	# def __init__(self, *args, **kwargs):
	# 	self.request = kwargs.pop('request', None)
	# 	return super().__init__(*args, **kwargs)

	# def save(self, request):
	# 	tiket = super().save(commit=False)
	# 	if tiket.mahasiswa is None:
	# 		tiket.mahasiswa = request.user
	# 	tiket.save()
	# 	return tiket

	class Meta :
		model = TiketModel
		fields = [
			# 'tiket',
			'judul',
			'aduan',
			'kategori',
			'file',
			# 'status',
		]

	judul = forms.CharField(widget=forms.TextInput(attrs={
                "placeholder": "Silakan Masukkan Aduan Anda",
                "class": "form-control"}))
	aduan = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'class':'form-control'}))
	kategori = forms.ChoiceField(choices=KATEGORI_LIST ,widget=forms.Select(attrs={'class':'form-control'}))
	# status = forms.ChoiceField(choices=STATUS ,widget=forms.Select(attrs={'class':'form-control'}))
	file = forms.FileField(widget=forms.FileInput(attrs={'class':'form-control-file'}))

apps/tiket/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.views.generic.base import View, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa


# Create your views here.
from apps.tiket import forms
from apps.tiket import models

def show_tiket(request):
    tikets = models.TiketModel.objects.all()
    movestates = []
    for tiket in tikets:
        move = models.MoveState.objects.filter(tiket_move=tiket).order_by('-updated')
        if move.exists():
            movestates.append(move.first())
    context = {
        'tikets':movestates
    }

    return render(request, 'tiket/report.html', context)

def pdf_report(request):
    tikets = models.TiketModel.objects.all()

    template_path = 'tiket/report2.html'
    movestates = []
    for tiket in tikets:
        move = models.MoveState.objects.filter(tiket_move=tiket).order_by('-updated')
        if move.exists():
            movestates.append(move.first())
    context = {
        'tikets':movestates
    }

    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"' # kalau mau langsung download tambahkan 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

class TiketUpdateView(UpdateView):
    form_class = forms.TiketForm
    model = models.TiketModel
    context_object_name = 'tiket'

    def get_template_names(self):
        test_group = Group.objects.get(name='mahasiswa')
        user_group = self.request.user.groups.all()

        if test_group in user_group:
            self.template_name = "tiket/tiket_update.html"
        else:
            self.template_name = "tiket/tiket_update_front.html"
        return super(TiketUpdateView, self).get_template_names()

class TiketDeleteView(DeleteView):
    model = models.TiketModel
    template_name = "tiket/tiket_delete_confirmation.html"
    success_url = reverse_lazy('tiket:manage')
    context_object_name = 'tiket'

class TiketManageView(ListView):
    # permission_required = ("tiket.manage_tiket")
    model = models.MoveState
    template_name = "tiket/tiket_manage.html"
    context_object_name = 'tiket_list'

    def get_context_data(self, **kwargs):
        context = super(TiketManageView, self).get_context_data(**kwargs)
        test_group = Group.objects.get(name='mahasiswa')
        user_group = self.request.user.groups.all()
        if test_group in user_group:
            tikets = models.TiketModel.objects.filter(mahasiswa=self.request.user)
        else : 
            tikets = models.TiketModel.objects.all()

        movestates = []
        for tiket in tikets:
            move = models.MoveState.objects.filter(tiket_move=tiket).order_by('-updated')
            if move.exists():
                movestates.append(move.first())
        context['status'] = movestates
        return context
        
class MoveStateCreateView(View):
    # permission_required = ("tiket.view_tiketmodel", "tiket.add_tiketmodel")
    template_name = "tiket/tiket_form_move_state.html"
    form = forms.MoveStateForm
    mode = None
    # model = models.MoveState
    context = {}

    def get(self, *args, **kwargs):
        self.context = {
            'form':self.form,
        }

        return render(self.request, self.template_name, self.context)

    move = None
    def post(self, *args, **kwargs):

        if kwargs.__contains__('update_id'):
            akun_update = models.MoveState.objects.get(id=kwargs['update_id'])
            self.form = forms.MoveStateForm(self.request.POST, instance=akun_update)
        else:
            self.form = forms.MoveStateForm(self.request.POST)
        tikets_id = models.MoveState.objects.get(id=kwargs['pk'])
        if self.form.is_valid():
            move = self.form.save(commit=False)
            move.tiket_move = tikets_id.tiket_move
            move.user_move = self.request.user
            print(move)
            move.save()

        return redirect('tiket:listmove')

class TiketCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ("tiket.view_tiketmodel", "tiket.add_tiketmodel")
    model = models.TiketModel
    form_class = forms.TiketForm
    template_name = "tiket/tiket_form.html"
    context_object_name = 'tiket'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.mahasiswa = self.request.user
        instance.tiket = get_random_string(10, 'abcdef0123456789')
        instance.save()
        States = models.State.objects.get(code_name=1)
        movestates =  models.MoveState.objects.create(tiket_move=instance, user_move=instance.mahasiswa, state_move=States)
        print(movestates)
        return super(TiketCreateView, self).form_valid(form)

class TiketMoveView(LoginRequiredMixin, ListView):
    model = models.MoveState
    context_object_name = 'tiket_list'
    template_name = None

    def get_context_data(self, **kwargs):
        context = super(TiketMoveView, self).get_context_data(**kwargs)
        test_group = Group.objects.get(name='mahasiswa')
        staf_group = Group.objects.get(name='staf')
        stafadmin_group = Group.objects.get(name='staf administrasi')
        stafnil_group = Group.objects.get(name='staf nilai')
        stafvisa_group = Group.objects.get(name='staf visa')
        user_group = self.request.user.groups.all()
        if test_group in user_group:
            tikets = models.TiketModel.objects.filter(mahasiswa=self.request.user)
            self.template_name = "tiket/tiket_move_mahasiswa.html"
        elif stafadmin_group in user_group:
            tikets = models.TiketModel.objects.filter(kategori='dokumen')
            self.template_name = "tiket/tiket_move.html"
        elif stafvisa_group in user_group:
            tikets = models.TiketModel.objects.filter(kategori='visa')
            self.template_name = "tiket/tiket_move.html"
        elif stafnil_group in user_group:
            tikets = models.TiketModel.objects.filter(kategori='nilai')
            self.template_name = "tiket/tiket_move.html"
        else :
            tikets = models.TiketModel.objects.all()
            self.template_name = "tiket/tiket_move.html"

        movestates = []
        for tiket in tikets:
            if staf_group in user_group:
                move = models.MoveState.objects.filter(tiket_move=tiket).exclude(state_move=1).order_by('-updated')
            else :
                move = models.MoveState.objects.filter(tiket_move=tiket).order_by('-updated')
            if move.exists():
                movestates.append(move.first())
        context['status'] = movestates
        return context

class TiketDetailView(DetailView):
    model = models.TiketModel
    template_name = "tiket/tiket_detail.html"
    context_object_name = 'tiket'

# confirmation finish for mahsasiswa
class MoveStateDetailView(DetailView):
    model = models.MoveState
    template_name = "tiket/tiket_detail_move_state.html"
    context_object_name = 'tiket'

class TiketNotDoneYet(View):
    model = models.MoveState
    form = forms.ConfirmationForm
    template_name = "tiket/tiket_belum_selesai.html"
    context_object_name = 'tiket'
    mode=0

    def get(self, *args, **kwargs):
        self.context = {
            'page_title':'Tambah Akun',
            'form':self.form,
        }

        return render(self.request, self.template_name, self.context)

    move = None

    def post(self, *args, **kwargs):
        self.form = forms.ConfirmationForm(self.request.POST)
        tikets_id = models.MoveState.objects.get(id=kwargs['pk'])
        if self.form.is_valid():
            move = self.form.save(commit=False)
            move.user_move = self.request.user
            move.tiket_move = tikets_id.tiket_move
            States = models.State.objects.get(code_name=2)
            move.state_move = States
            move.save()
            print(move)

        return redirect('tiket:listmove')

class TiketDone(View):
    model = models.MoveState
    form = forms.ConfirmationForm
    template_name = "tiket/tiket_sudah_selesai.html"
    context_object_name = 'tiket'
    mode=0

    def get(self, *args, **kwargs):
        self.context = {
            'page_title':'Tambah Akun',
            'form':self.form,
        }

        return render(self.request, self.template_name, self.context)

    move = None
    def post(self, *args, **kwargs):
        self.form = forms.ConfirmationForm(self.request.POST)
        tikets_id = models.MoveState.objects.get(id=kwargs['pk'])
        if self.form.is_valid():
            move = self.form.save(commit=False)
            move.user_move = self.request.user
            move.tiket_move = tikets_id.tiket_move
            States = models.State.objects.get(code_name=5)
            move.state_move = States
            print(move)
            move.save()

        return redirect('tiket:listmove')

apps/templates/tiket/tiket_detail_move_state.html
{% extends "layouts/base.html" %}

{% block title %} Ticket Detail {% endblock title %}

{% block stylesheets %} {% endblock stylesheets %}

{% block content %}
    <div class="pcoded-main-container">
    	<div class="pcoded-wrapper">
    		<div class="pcoded-content">
    			<!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h3 class="m-b-10">Ticket Detail</h3>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="javascript:" disabled>Ticket</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">Ticket Detail</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                    	<div class="page-wrapper">
                    		<div class="row">
                    			<div class="col-md-12">
                    				<div class="card">
                    					<div class="card-header">
                                            <h5>Ticket Detail</h5>
                                        </div>
                                        <div class="card-block table-border-style">
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                        <tr> 
                                                            <th>Tentang</th>
                                                            <th class="text-center">Isi</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <th scope="row">Judul Tiket</th>
                                                            <td class="text-center">{{tiket.tiket_move.judul}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">Tiket</th>
                                                            <td class="text-center">{{tiket.tiket_move.tiket}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">Kategori</th>
                                                            <td class="text-center">{{tiket.tiket_move.kategori}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">Tanggal Dibuat</th>
                                                            <td class="text-center">{{tiket.tiket_move.date}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">Pembuat Aduan</th>
                                                            {% if not tiket.tiket_move.mahasiswa.mahasiswa.nim %}
                                                                <td class="text-center">{{tiket.tiket_move.mahasiswa.username}}</td>
                                                            {% else %}
                                                                <td class="text-center">{{tiket.tiket_move.mahasiswa.get_full_name}}</td>
                                                            {% endif %}
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">NIM Pembuat Aduan</th>
                                                            {% if not tiket.tiket_move.mahasiswa.mahasiswa.nim %}
                                                                <td class="text-center">Front Desk</td>
                                                                {% else %}
                                                                <td class="text-center">{{tiket.tiket_move.mahasiswa.mahasiswa.nim}}</td>
                                                            {% endif %}
                                                        </tr>
                                                        <tr>
                                                            <th scope="row">Email Pembuat Aduan</th>
                                                            <td class="text-center">{{tiket.tiket_move.mahasiswa.mahasiswa.user.email}}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="col-sm-12">
                                            <div class="accordion" id="accordionExample">
                                                {% if request.user.mahasiswa.nim %}
                                                <div class="card">
                                                    <div class="card-header" id="headingOne">
                                                        <h5 class="mb-0"><a href="#!" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Komentar dari Staf</a></h5>
                                                    </div>
                                                    <div id="collapseOne" class=" card-body collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">{{tiket.comment}}
                                                    </div>
                                                </div>
                                            {% endif %}
                                                <div class="card">
                                                    <div class="card-header" id="headingTwo">
                                                        <h5 class="mb-0"><a href="#!" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">Rincian Aduan</a></h5>
                                                    </div>
                                                    <div id="collapseTwo" class=" card-body collapse show" aria-labelledby="headingTwo" data-parent="#accordionExample">{{tiket.tiket_move.aduan}}
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        <a href="{% url 'tiket:listmove' %}" class="btn btn-dark mr-2">back</a>
                                        {% if request.user.mahasiswa.nim %}
                                            <a href="{% url 'tiket:tiketclosed' tiket.id %}" class="btn btn-info mr-2 text-dark">Done</a>
                                            <a href="{% url 'tiket:tiketopen' tiket.id %}" class="btn btn-warning mr-2 text-dark">Not Yet</a>
                                        {% else %}
                                            <a href="{% url 'tiket:createmove' tiket.id %}" class="btn btn-outline-danger mr-2">kerjakan Tiket</a>
                                        {% endif %}
                                        </div>
                    				</div>
                    			</div>
                    		</div>
                    	</div>
                    </div>
    		</div>
    	</div>
    </div>
{% endblock content %}

{% block javascripts %} {% endblock javascripts %}

apps/templates/tiket/tiket_manage.html
{% extends "layouts/base.html" %}

{% block title %} All Ticket {% endblock title %}

{% block stylesheets %} {% endblock stylesheets %}

{% block content %}
    <div class="pcoded-main-container">
    	<div class="pcoded-wrapper">
    		<div class="pcoded-content">
    			<!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h5 class="m-b-10">All Tiket</h5>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="javascript:" disabled>Ticket</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">All Ticket</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                    	<div class="page-wrapper">
                    		<div class="row">
                    			<div class="col-md-12">
                    				<div class="card">
                    					<div class="card-header">
                                            <h5>All Ticket</h5>
                                        </div>
                                        <div class="card-block table-border-style">
                                        	<div class="table-responsive">
                                                <table id="basic-datatables" class="table table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Ticket ID</th>
                                                            <th>Reported by</th>
                                                            <th>NIM</th>
                                                            <th>complaint type</th>
                                                            <th>Category</th>
                                                            <th>Status</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                            {% for tiket in status %}
                                                        <tr>
                                                            <th scope="row"><a href="{% url 'tiket:detail' tiket.tiket_move.slug %}" class="text-info">{{tiket.tiket_move.tiket}}</a></th>
                                                            <td>{{tiket.tiket_move.mahasiswa}}</td>
                                                            {% if not tiket.tiket_move.mahasiswa.mahasiswa.nim %}
                                                                <td>Front Desk</td>
                                                            {% else %}
                                                                <td>{{tiket.tiket_move.mahasiswa.mahasiswa.nim}}</td>
                                                            {% endif %}
                                                            <td>{{tiket.tiket_move.judul}}</td>
                                                            <td>{{tiket.tiket_move.kategori}}</td>
                                                            <td>{{tiket.state_move.state_name}}</td>
                                                            <td>
                                                                <div class="btn-group mb-2 mr-2">
                                                                <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Info</button>
                                                                    <div class="dropdown-menu">
                                                                        <!-- <a class="dropdown-item" href="{% url 'tiket:update' tiket.id %}">Edit Ticket</a> -->
                                                                        <a class="dropdown-item text-warning" href="{% url 'tiket:delete' tiket.tiket_move.id %}">Delete Tiket</a>
                                                                        <a class="dropdown-item text-info" href="{% url 'tiket:createmove' tiket.id %}">Buat Status</a>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                    				</div>
                    			</div>
                    		</div>
                    	</div>
                    </div>
    		</div>
    	</div>
    </div>
{% endblock content %}

{% block javascripts %}
    <script >
        $(document).ready(function() {
            $('#basic-datatables').DataTable({
            });
        });
    </script>
{% endblock javascripts %}